name: Docker CI/CD

on:
    pull_request:
        branches: [ "**" ]
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Docker Image Building and Publishing
                id:   docker_build
                uses: docker/build-push-action@v2
                with:
                    push: false
                    tags: juftin/camply:latest
